# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 09:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, default=None, max_length=24, null=True)),
            ],
            options={
                'verbose_name': 'Размер цвет коробки',
                'verbose_name_plural': 'Размеры и цвета коробок',
            },
        ),
        migrations.CreateModel(
            name='BoxSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, default=None, max_length=24, null=True)),
            ],
            options={
                'verbose_name': 'Размер коробки',
                'verbose_name_plural': 'Размеры коробок',
            },
        ),
        migrations.CreateModel(
            name='CompositionColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=24, null=True)),
            ],
            options={
                'verbose_name': 'Цветовая гамма компоции',
                'verbose_name_plural': 'Цветовые гаммы',
            },
        ),
        migrations.CreateModel(
            name='FlowerPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=24, null=True)),
            ],
            options={
                'verbose_name': 'Предпочтение по цветам',
                'verbose_name_plural': 'Предпочтения по цветам',
            },
        ),
        migrations.CreateModel(
            name='IndividualComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('customer_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('customer_phone_number', models.CharField(blank=True, default=None, max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('box_color', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.BoxColor')),
                ('box_size', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.BoxSize')),
                ('composition_color', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.CompositionColor')),
            ],
            options={
                'verbose_name': 'Индивидуальная композиция',
                'verbose_name_plural': 'Индивидуальные композиции',
            },
        ),
        migrations.AddField(
            model_name='flowerpreference',
            name='individual_composition',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.IndividualComposition'),
        ),
    ]
