# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowerpreference',
            old_name='name',
            new_name='flower_preference',
        ),
    ]
