# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170511_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowerpreference',
            name='individual_composition',
        ),
        migrations.AlterField(
            model_name='individualcomposition',
            name='box_color',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='individualcomposition',
            name='box_size',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='individualcomposition',
            name='composition_color',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='BoxColor',
        ),
        migrations.DeleteModel(
            name='BoxSize',
        ),
        migrations.DeleteModel(
            name='CompositionColor',
        ),
        migrations.DeleteModel(
            name='FlowerPreference',
        ),
    ]
