# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170430_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='address',
        ),
    ]
