# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170511_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualcomposition',
            name='flower_preferernce',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
