# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_individualcomposition_flower_preferernce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualcomposition',
            old_name='flower_preferernce',
            new_name='flower_preference',
        ),
    ]
