# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20170430_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время и дата доставки'),
        ),
    ]
